#server:
#  port: ${PORT:8980}
#external:
#  amqp:
#    exchange:
#      fanout:
#        auto-delete: false
#    bind:
#      route-key: "*"
#    queue: expedia.default.queue
#  event-sourcing:
#    events-collection-name: connectors-events
#    snapshot-collection-name: connectors-events-snapshots
#spring:
#  data:
#    mongodb:
#      uri: ${MONGODB_URI:mongodb://localhost:27017/continents}
#      database: ${MONGO_DATABASE:continents}
#  rabbitmq:
#    host: localhost
#    port: 5672
#    virtual-host: /
#    username: guest
#    password: guest
#  application:
#    name: connectors
#axon:
#  amqp:
#    exchange: expedia.events.fanout.exchange
#    transaction-mode: none
#    durable-messages: true
#  metrics:
#    auto-configuration:
#      enabled: true
#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2